name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: stabbles/pkg-example:latest
    steps:
      - uses: actions/checkout@v2
      - name: Make OpenMPI happy
        run: |
          # TODO: should be able to do without ...
          apt-get update -qq && apt-get install -qq ssh
      - name: Setup Spack
        run: |
          /opt/spack/bin/spack --color=always -e ./tools/environments/ci/ repo add ./tools/spack
          /opt/spack/bin/spack --color=always -e ./tools/environments/ci/ concretize
      - name: Build and test
        run: |
          # again, openmpi needs this.
          export OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
          /opt/spack/bin/spack --color=always -e ./tools/environments/ci/ install -v --test=root mypkg@main